trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: helm_repo
  value: oci://ghcr.io/garyrizzo1992 

steps:
- checkout: self
  persistCredentials: true
- script: |
    git config --global user.email azure.devops@garyrizzo.com & git config --global user.name "Azure Devops"
- script: |
    helm registry login ghcr.io/garyrizzo1992 --username garyrizzo1992 --password $(GITHUB_TOKEN_REGISTRY)
    helm package -u .
    helm push nginx-helm-$(yq -r ".version" Chart.yaml).tgz ${{ variables.helm_repo }}
  displayName: 'Run a multi-line script'
  workingDirectory: nginx-helm
    
