pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-garyrizzo1992'
    repository: 'top10crypto'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'