trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: credentials
- name: helm_repo
  value: ghcr.io/garyrizzo1992 
- name: helm_repo_name
  value: nginx-helm
- name: bump
  value: minor
- name: helm_chart_version
  value: latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-garyrizzo1992'
    repository: 'garyrizzo1992/top10crypto'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- bash: |
   rm /home/vsts/.gitconfig || true
   rm /home/vsts/.gitconfig.lock || true
   git config --global user.email azure.devops@garyrizzo.com & git config --global user.name "Azure Devops"
  displayName: 'git configure'
- bash: |
   git clone https://x-token-auth:$(BITBUCKET_ACCESS_TOKEN)@bitbucket.org/garyrizzo1992/nginx.git
   cd nginx
   yq -i ".image.tag = \"$(Build.BuildId)\"" nginx-helm/values.yaml 
   git add nginx-helm/values.yaml 
   git commit -m "AUTOMATED - Bumping image tag in values file" || true
   git push origin main
  displayName: 'Git clone'
- bash: "helm registry login ghcr.io/garyrizzo1992 --username garyrizzo1992 --password $(GITHUB_TOKEN_REGISTRY)"
  displayName: Helm Login
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'do-stage-flows-1711100225852'
    namespace: 'flows'
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'oci://${{ variables.helm_repo }}/${{ variables.helm_repo_name }}'
    chartVersion: '{{ variables.helm_chart_version }}'
    releaseName: 'nginx-helm'
    valueFile: 'nginx-helm/values.yaml'